### ISSUE TITLE
你有压测过吗，我怎么压测感觉webflux 性能严重不行啊

### ISSUE THREAD

**Issue by yu199195** [zicat/spring-webflux-research#1]

**Comment by zicat** [comment]
我有压过，极限性能比Servlet模型的tomcat和jetty都要好，压测时要注意设置Loop线程数和work线程数，Loop线程数控制在少量，和系统核数相同较为合理，work线程看具体业务，如果阻塞io业务较少就可以少一点。这两个线程数量如果设置不当，性能会很差，我之前也遇到过这个问题。
